package com.oakonell.dndcharacter.model.character;

/**
 * Created by Rob on 3/21/2016.
 */
public enum CustomAdjustmentType {
    ROOT_ACS, INITIATIVE, MODIFYING_ACS,
    STAT_STRENGTH, STAT_DEXTERITY, STAT_CONSTITUTION, STAT_INTELLIGENCE, STAT_WISDOM, PASSIVE_PERCEPTION, STAT_CHARISMA,
    SPEED_WALK, SPEED_FLY, SPEED_SWIM, SPEED_BURROW, SPEED_CLIMB, SPEED_CRAWL
}
